version: '3'

services:

  squidweb:
    build:
      context: ./Template
      dockerfile: Dockerfile
    
    image: template

    expose:
    - "80"

    environment:
    - VIRTUAL_HOST=www.terrorsquid.net
    - ConnectionStrings_default=redis

    restart: always

networks:
      default:
        external:
          name: terrorsquid